export const routeTreeGenTemplate = (): string =>
  `/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make direct changes to this file.
// Any changes made to this file will be overwritten the next time the route tree is regenerated.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'

const rootRouteChildren = {
  IndexRoute: IndexRouteImport,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
`;

export const rootRouteTemplate = (): string =>
  `import { createRootRoute, Outlet } from '@tanstack/react-router';
import { TanStackRouterDevtools } from '@tanstack/router-devtools';

export const Route = createRootRoute({
  component: () => (
    <>
      <Outlet />
      <TanStackRouterDevtools />
    </>
  ),
});
`;

export const indexRouteFsdTemplate = (): string =>
  `import { createFileRoute } from '@tanstack/react-router';
import { HomePage } from '@/pages/home';

export const Route = createFileRoute('/')({
  component: HomePage,
});
`;

export const indexRouteBprTemplate = (): string =>
  `import { createFileRoute } from '@tanstack/react-router';
import Home from '@/pages/Home';

export const Route = createFileRoute('/')({
  component: Home,
});
`;
