import { FileMap } from '@src/scaffold/utils';

// Project-type-agnostic pieces of the Claude Code harness (docs knowledge base,
// docs tooling, settings, docs skill, docs-writer agent, memory seeds).
// Project-specific pieces (CLAUDE.md, conventions skill, dev agent, test-writer)
// are rendered by each project type and passed in via ClaudeHarnessParams.

export const STATUS_ENUM = ['active', 'draft', 'deprecated'];
export const LANG_ENUM = ['en', 'vi'];

export interface ClaudeHarnessParams {
  projectName: string;
  slug: string;
  flowEnum: string[];
  layerEnum: string[];
  reminderTrigger: string;
  claudeMd: string;
  conventionsSkill: string;
  devAgent: string;
  seedDocs: FileMap;
  testing?: {
    testWriterAgent: string;
    testAuthorSkill: string;
  };
}

// ---------------------------------------------------------------------------
// docs/ knowledge base
// ---------------------------------------------------------------------------

const docsTemplateMdTemplate = (flowEnum: string[], layerEnum: string[]): string =>
  `---
title: <Concise title; mirror the H1 below>
feature: _app        # feature folder name under docs/features/ | _app (cross-cutting)
flow: _meta          # enum: ${flowEnum.join(' | ')}
layer: _cross        # enum: ${layerEnum.join(' | ')}
status: active       # enum: ${STATUS_ENUM.join(' | ')}
lang: en             # enum: ${LANG_ENUM.join(' | ')}
related: []          # array of doc paths relative to docs/
keywords: []         # lowercase kebab-case; prefer real symbol/file names from the repo
updated: YYYY-MM-DD
---

# <Title>

## Context
What problem was being solved and why it was non-obvious.

## Root Cause / Key Finding
The core discovery that unblocked the task.

## Solution / Pattern
What was implemented and why.

## Key Decisions
Trade-offs made and alternatives rejected.

## Related Files
- path/to/relevant/file.ts
`;

const docsReadmeTemplate = (): string =>
  `# Docs — Knowledge Base

Frontmatter-indexed task docs. \`INDEX.md\` is auto-generated — never hand-edit it.

## Where to put new docs

| Doc type | Directory |
|---|---|
| Feature spec / feature-scoped finding | \`docs/features/<feature>/\` |
| Cross-cutting architecture / patterns | \`docs/architecture/\` |
| Onboarding material | \`docs/onboarding/\` |

## File naming

| Case | Name |
|---|---|
| Main spec of a feature | \`<feature>.spec.en.md\` |
| Spec translation alongside | \`<feature>.spec.vi.md\` |
| Topic doc (English) | \`<topic>.en.md\` |
| Translation alongside | \`<topic>.vi.md\` |

## Workflow

1. Copy \`docs/_template.md\`, fill ALL frontmatter fields (the index and lint are built from it).
2. Save to the right directory per the table above.
3. \`npm run docs:index\` — regenerates \`INDEX.md\`.
4. \`npm run docs:lint\` — must pass before committing.
5. Commit the doc and \`INDEX.md\` together.
`;

const docsIndexPlaceholderTemplate = (): string =>
  `# Docs Index

> Auto-generated by \`.claude/scripts/build-docs-index.mjs\` — do not edit by hand.
> Run \`npm run docs:index\` to regenerate.
`;

// ---------------------------------------------------------------------------
// Docs tooling (.claude/scripts/)
// ---------------------------------------------------------------------------

const docsSharedMjsTemplate = (flowEnum: string[], layerEnum: string[]): string =>
  `// Shared helpers for docs tooling — single source of truth for the frontmatter schema.
import { readdirSync, readFileSync } from 'fs';
import { join, relative } from 'path';

export const DOCS_DIR = 'docs';
export const SKIP_FILES = new Set(['INDEX.md', 'README.md', '_template.md']);

export const ENUMS = {
  flow: ${JSON.stringify(flowEnum)},
  layer: ${JSON.stringify(layerEnum)},
  status: ${JSON.stringify(STATUS_ENUM)},
  lang: ${JSON.stringify(LANG_ENUM)},
};

export const REQUIRED_FIELDS = ['title', 'feature', 'flow', 'layer', 'status', 'lang', 'keywords', 'updated'];

// Minimal YAML frontmatter parser: scalar values and inline arrays ([a, b]).
export function parseFrontmatter(content) {
  const match = content.match(/^---\\n([\\s\\S]*?)\\n---/);
  if (!match) return null;
  const meta = {};
  for (const line of match[1].split('\\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).replace(/\\s+#.*$/, '').trim();
    if (!key) continue;
    if (value.startsWith('[') && value.endsWith(']')) {
      const inner = value.slice(1, -1).trim();
      meta[key] = inner === ''
        ? []
        : inner.split(',').map((item) => item.trim().replace(/^['"]|['"]$/g, ''));
    } else {
      meta[key] = value.replace(/^['"]|['"]$/g, '');
    }
  }
  return meta;
}

export function firstHeading(content) {
  const match = content.match(/^#\\s+(.+)$/m);
  return match ? match[1].trim() : null;
}

// Walks docs/**/*.md (excluding SKIP_FILES) and returns parsed records.
export function walkDocs(dir = DOCS_DIR, records = []) {
  for (const item of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, item.name);
    if (item.isDirectory()) {
      walkDocs(fullPath, records);
    } else if (item.name.endsWith('.md') && !SKIP_FILES.has(item.name)) {
      const content = readFileSync(fullPath, 'utf-8');
      records.push({
        path: relative(DOCS_DIR, fullPath),
        fm: parseFrontmatter(content),
        title: firstHeading(content),
      });
    }
  }
  return records;
}
`;

const buildDocsIndexMjsTemplate = (): string =>
  `// Regenerates docs/INDEX.md from frontmatter. Deterministic (sorted) so diffs stay clean.
// Run via: npm run docs:index
import { writeFileSync } from 'fs';
import { join } from 'path';
import { walkDocs, DOCS_DIR } from './_docs-shared.mjs';

const records = walkDocs().sort((a, b) => a.path.localeCompare(b.path));
const withFm = records.filter((record) => record.fm !== null).length;
const today = new Date().toISOString().slice(0, 10);

function entryLine(record) {
  const fm = record.fm ?? {};
  const title = fm.title ?? record.title ?? record.path;
  const tags = ['feature', 'flow', 'layer']
    .map((key) => '\`' + key + ':' + (fm[key] ?? '_unknown') + '\`')
    .join(' ');
  const keywords = Array.isArray(fm.keywords) && fm.keywords.length > 0
    ? ' — ' + fm.keywords.join(', ')
    : '';
  return '- [' + title + '](' + record.path + ') — ' + tags + keywords;
}

function section(heading, key) {
  const groups = new Map();
  for (const record of records) {
    const groupKey = record.fm?.[key] ?? '_unknown';
    if (!groups.has(groupKey)) groups.set(groupKey, []);
    groups.get(groupKey).push(record);
  }
  const lines = ['## ' + heading, ''];
  for (const [name, group] of [...groups.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push('### ' + name + ' (' + group.length + ')');
    lines.push(...group.map(entryLine));
    lines.push('');
  }
  return lines;
}

function keywordIndex() {
  const map = new Map();
  for (const record of records) {
    for (const keyword of record.fm?.keywords ?? []) {
      if (!map.has(keyword)) map.set(keyword, []);
      map.get(keyword).push(record.path);
    }
  }
  if (map.size === 0) return [];
  return [
    '## Keyword Index',
    ...[...map.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([keyword, paths]) =>
        '- \`' + keyword + '\` → ' + paths.map((path) => '[' + path + '](' + path + ')').join(', ')
      ),
    '',
  ];
}

const lines = [
  '# Docs Index',
  '',
  '> Auto-generated by \`.claude/scripts/build-docs-index.mjs\` — do not edit by hand.',
  '> Generated: ' + today + ' from ' + records.length + ' files (' + withFm + ' with frontmatter, ' + (records.length - withFm) + ' without).',
  '',
];

if (records.length === 0) {
  lines.push('_(No docs yet. Copy docs/_template.md to get started.)_', '');
} else {
  lines.push(...section('By Feature', 'feature'));
  lines.push(...section('By Flow', 'flow'));
  lines.push(...section('By Layer', 'layer'));
  lines.push(...keywordIndex());
}

writeFileSync(join(DOCS_DIR, 'INDEX.md'), lines.join('\\n').replace(/\\n+$/, '\\n'));
console.log('docs/INDEX.md updated — ' + records.length + ' doc(s), ' + withFm + ' with frontmatter.');
`;

const lintDocsFrontmatterMjsTemplate = (): string =>
  `// Validates every doc against the frontmatter schema. Exits non-zero on violation → CI-ready.
// Run via: npm run docs:lint
import { existsSync } from 'fs';
import { join } from 'path';
import { walkDocs, ENUMS, REQUIRED_FIELDS, DOCS_DIR } from './_docs-shared.mjs';

const errors = [];

for (const record of walkDocs()) {
  const where = 'docs/' + record.path;
  if (record.fm === null) {
    errors.push(where + ': missing frontmatter block');
    continue;
  }
  for (const field of REQUIRED_FIELDS) {
    if (record.fm[field] === undefined || record.fm[field] === '') {
      errors.push(where + ': missing required field "' + field + '"');
    }
  }
  for (const [field, allowed] of Object.entries(ENUMS)) {
    const value = record.fm[field];
    if (value !== undefined && !allowed.includes(value)) {
      errors.push(where + ': invalid ' + field + ' "' + value + '" (allowed: ' + allowed.join(', ') + ')');
    }
  }
  if (record.fm.updated !== undefined && !/^\\d{4}-\\d{2}-\\d{2}$/.test(record.fm.updated)) {
    errors.push(where + ': "updated" must be YYYY-MM-DD (got "' + record.fm.updated + '")');
  }
  if (Array.isArray(record.fm.keywords)) {
    for (const keyword of record.fm.keywords) {
      if (keyword !== keyword.toLowerCase()) {
        errors.push(where + ': keyword "' + keyword + '" must be lowercase');
      }
    }
  }
  for (const related of record.fm.related ?? []) {
    if (!existsSync(join(DOCS_DIR, related))) {
      errors.push(where + ': related path "' + related + '" does not exist under docs/');
    }
  }
}

if (errors.length > 0) {
  console.error('docs:lint failed with ' + errors.length + ' error(s):');
  for (const error of errors) console.error('  - ' + error);
  process.exit(1);
}
console.log('docs:lint passed.');
`;

const docsFirstReminderShTemplate = (trigger: string): string =>
  `#!/usr/bin/env bash
# UserPromptSubmit hook: inject a docs-first reminder when the prompt mentions
# a documented feature/flow/domain topic. Silent otherwise to avoid noise.
# The harness runs this on every user prompt, so the reminder cannot be skipped.
payload="$(cat)"

# Keep in sync with feature folders under docs/features/ + key domain nouns.
# Add an alternation entry whenever a new feature doc is created.
trigger='${trigger}'

if echo "$payload" | grep -iqE "$trigger"; then
  cat <<'EOF'
[docs-first guard] This request appears to touch a documented feature/flow.
BEFORE opening source code:
  1. Read docs/INDEX.md (grouped by feature / flow / layer + keyword index).
  2. Narrow with frontmatter grep, e.g.:
       grep -rlE '^feature: <feature>' docs/ | xargs grep -lE '^flow: <flow>'
  3. Read candidate doc bodies (<=5 files), then follow \`related:\` links.
  4. Open source only if docs are insufficient — and state what the docs covered.
EOF
fi
exit 0
`;

// ---------------------------------------------------------------------------
// .claude/settings.json
// ---------------------------------------------------------------------------

const claudeSettingsTemplate = (): string =>
  JSON.stringify(
    {
      permissions: {
        deny: [
          'Bash(git push*)',
          'Bash(git commit*)',
          'Bash(git merge*)',
          'Bash(git rebase*)',
          'Bash(git tag*)',
          'Bash(git branch -D*)',
          'Bash(git branch -d*)',
          'Bash(git reset --hard*)',
          'Bash(git clean*)',
        ],
        allow: [],
      },
      hooks: {
        UserPromptSubmit: [
          {
            hooks: [
              {
                type: 'command',
                command: 'bash "$CLAUDE_PROJECT_DIR/.claude/scripts/docs-first-reminder.sh"',
              },
            ],
          },
        ],
      },
      sandbox: {
        filesystem: { denyRead: ['**/.env', '**/.env.*'] },
      },
    },
    null,
    2
  );

// ---------------------------------------------------------------------------
// Docs skill + docs-writer agent + memory seeds
// ---------------------------------------------------------------------------

const docsSkillTemplate = (
  projectName: string,
  slug: string,
  flowEnum: string[],
  layerEnum: string[]
): string =>
  `---
name: ${slug}-docs
description: How to find and write knowledge-base docs for ${projectName}. Use when asked "is there a doc about…", "explain the X feature/flow", "document this", "write a spec", or the Vietnamese equivalents ("có tài liệu về…", "giải thích flow…", "viết docs/spec…"). Also use before modifying any documented feature.
---

# ${projectName} Docs Guide

## Finding docs (DOCS-FIRST)

1. Start at \`docs/INDEX.md\` — grouped By Feature / By Flow / By Layer, plus a keyword reverse-index.
2. Narrow with frontmatter grep (never semantic-search bodies):
   \`\`\`bash
   grep -rlE '^feature: home' docs/
   grep -rlE '^feature: home' docs/ | xargs grep -lE '^flow: ui'
   \`\`\`
3. Read candidate doc bodies (≤5 files), then follow their \`related:\` links.
4. Only open source when docs are insufficient — and state what the docs already covered.

## Writing docs

1. Copy \`docs/_template.md\`; every field is required (see \`docs/README.md\` for placement + naming).
2. Frontmatter axes: \`feature\` (folder under docs/features/ or \`_app\`), \`flow\` (${flowEnum.join('/')}), \`layer\` (${layerEnum.join('/')}).
3. Keywords: lowercase, prefer real symbol/file names an engineer would grep for.
4. Rebuild + validate, then commit doc and INDEX.md together:
   \`\`\`bash
   npm run docs:index && npm run docs:lint
   \`\`\`
`;

const docsWriterAgentTemplate = (projectName: string, slug: string): string =>
  `---
name: docs-writer
description: "Documentation agent for ${projectName} — analyzes requirements from any source (conversation, tickets, Slack) and maintains docs/. <example>user: 'Here are the requirements for the profile page, write them up' → docs-writer <commentary>synthesizing requirements into a feature spec</commentary></example> <example>user: 'We just finished the auth refactor, document what changed' → docs-writer <commentary>post-task knowledge capture</commentary></example> <example>user: 'Update the home spec — the hero section was redesigned' → docs-writer <commentary>doc maintenance</commentary></example>"
model: haiku
memory: project
---

You are the documentation agent for ${projectName}. You own \`docs/\`.

## Onboarding protocol

1. Read \`.claude/agent-memory/docs-writer/MEMORY.md\`.
2. Read \`docs/README.md\` (placement + naming rules) and \`docs/INDEX.md\` (what already exists).
3. Load the \`${slug}-docs\` skill.

## Workflow

1. Understand the requirement; if sources conflict, surface the conflict instead of guessing.
2. Check INDEX.md for an existing doc to update before creating a new one.
3. Copy \`docs/_template.md\`; fill ALL frontmatter fields (feature, flow, layer, status, lang, keywords, updated). Specs describe WHAT, not HOW.
4. Save per docs/README.md rules: \`docs/features/<feature>/<feature>.spec.en.md\` for feature specs, \`<topic>.en.md\` for findings, \`docs/architecture/\` for cross-cutting topics.
5. Run \`npm run docs:index\` then \`npm run docs:lint\` — both must succeed.
6. If the feature introduces new domain nouns, add them to the \`trigger\` list in \`.claude/scripts/docs-first-reminder.sh\`.
7. Report created/updated paths. Append lessons to \`.claude/agent-memory/docs-writer/MEMORY.md\`.

## Hard rules

- Never hand-edit \`docs/INDEX.md\`.
- Never edit application code — you write markdown and run the docs scripts only.
- Never commit or push.
`;

const agentMemorySeedTemplate = (agentName: string): string =>
  `# ${agentName} — Agent Memory

Append durable, non-obvious gotchas and patterns discovered while working — one bullet each, newest first. Link related docs/ files. Read this file at the start of every session.

_(no entries yet)_
`;

// ---------------------------------------------------------------------------
// File map
// ---------------------------------------------------------------------------

export const buildClaudeFileMap = (params: ClaudeHarnessParams): FileMap => {
  const { projectName, slug, flowEnum, layerEnum } = params;
  const files: FileMap = [
    { relativePath: 'CLAUDE.md', content: params.claudeMd },
    { relativePath: '.claude/settings.json', content: claudeSettingsTemplate() },
    { relativePath: '.claude/scripts/_docs-shared.mjs', content: docsSharedMjsTemplate(flowEnum, layerEnum) },
    { relativePath: '.claude/scripts/build-docs-index.mjs', content: buildDocsIndexMjsTemplate() },
    { relativePath: '.claude/scripts/lint-docs-frontmatter.mjs', content: lintDocsFrontmatterMjsTemplate() },
    { relativePath: '.claude/scripts/docs-first-reminder.sh', content: docsFirstReminderShTemplate(params.reminderTrigger) },
    { relativePath: `.claude/skills/${slug}-conventions/SKILL.md`, content: params.conventionsSkill },
    { relativePath: `.claude/skills/${slug}-docs/SKILL.md`, content: docsSkillTemplate(projectName, slug, flowEnum, layerEnum) },
    { relativePath: '.claude/agents/dev.md', content: params.devAgent },
    { relativePath: '.claude/agents/docs-writer.md', content: docsWriterAgentTemplate(projectName, slug) },
    { relativePath: '.claude/agent-memory/dev/MEMORY.md', content: agentMemorySeedTemplate('dev') },
    { relativePath: '.claude/agent-memory/docs-writer/MEMORY.md', content: agentMemorySeedTemplate('docs-writer') },
    { relativePath: 'docs/README.md', content: docsReadmeTemplate() },
    { relativePath: 'docs/INDEX.md', content: docsIndexPlaceholderTemplate() },
    { relativePath: 'docs/_template.md', content: docsTemplateMdTemplate(flowEnum, layerEnum) },
    ...params.seedDocs,
  ];

  if (params.testing) {
    files.push(
      { relativePath: '.claude/agents/test-writer.md', content: params.testing.testWriterAgent },
      { relativePath: '.claude/agent-memory/test-writer/MEMORY.md', content: agentMemorySeedTemplate('test-writer') },
      { relativePath: `.claude/skills/${slug}-test-author/SKILL.md`, content: params.testing.testAuthorSkill }
    );
  }

  return files;
};
